Assets/!Scripts/Enemies/SpecificEnemyStuff/WorkerBehav.cs, Assets/!Scripts/Enemies/SpecificEnemyStuff/WorkerBehav.cs.meta
Simple Worker script, followed naming conventions from SplitterBehav. Want to chat about setting up an AIController state machine script at meeting today :)
=> Added WorkerBehav script

Assets/!Prefabs/Enemies/Splitter/LittleSplitter.prefab, Assets/!Prefabs/Enemies/Splitter/LittleSplitter.prefab.meta, Assets/!Scenes/EnemyPlayground.unity, Assets/!Scripts/Enemies/BasicEnemyStuff/EnemyDebug.cs, Assets/!Scripts/Enemies/BasicEnemyStuff/EnemyDebug.cs.meta, Assets/!Scripts/Enemies/BasicEnemyStuff/EnemyWander.cs, Assets/!Scripts/Enemies/SpecificEnemyStuff/LittleSplitterBehav.cs, Assets/!Scripts/Enemies/SpecificEnemyStuff/LittleSplitterBehav.cs.meta, ProjectSettings/TagManager.asset
=> Little Splitters done

Assets/!Scenes/WorkerTestScene.unity, Assets/!Scenes/WorkerTestScene.unity.meta, Assets/!Scripts/Enemies/BasicEnemyStuff/AIController.cs, Assets/!Scripts/Enemies/BasicEnemyStuff/AIController.cs.meta, Assets/!Scripts/Enemies/BasicEnemyStuff/BaseEnemy.cs, Assets/!Scripts/Enemies/BasicEnemyStuff/BaseEnemy.cs.meta, Assets/!Scripts/Enemies/SpecificEnemyStuff/WorkerBehav.cs, Assets/!Scripts/PlayerHealth.cs, Assets/!Scripts/PlayerHealth.cs.meta
Added in a separate test scene for Worker, added state machine & ai controller & temporary player health
=> changes made to WorkerBehav

Assets/!Scripts/UI/ButtonCooldown.cs, Assets/!Scripts/UI/ButtonCooldown.cs.meta, Assets/!Scripts/UI/HealthBar.cs, Assets/!Scripts/UI/HealthBar.cs.meta
Player health, health bar, and ability cooldowns
=> Health and Abilities

Assets/!Scenes/EnemyPlayground.unity, Assets/!Scripts/Enemies/BasicEnemyStuff/EnemyWaypoints.cs, Assets/!Scripts/Enemies/BasicEnemyStuff/EnemyWaypoints.cs.meta, Assets/!Scripts/Enemies/SpecificEnemyStuff/SplitterWayPointBehav.cs, Assets/!Scripts/Enemies/SpecificEnemyStuff/SplitterWayPointBehav.cs.meta
=> Enemy Way Points added

Assets/!Scripts/Enemies/SpecificEnemyStuff/WorkerBehav.cs
Player collision issue fixed, new aggroRange added. Approved by GP, more to come re: health bar
=> Worker adjustments

Assets/!Scenes/MainMenu.unity, Assets/!Scenes/SaveandSaveAndSaveAndSaver.unity, Assets/!Scripts/AsadStuff/CheckpointSystem.cs, Assets/!Scripts/AsadStuff/Coin.cs, Assets/!Scripts/AsadStuff/Coin.cs.meta, Assets/!Scripts/AsadStuff/Collectible.cs, Assets/!Scripts/AsadStuff/Collectible.cs.meta, Assets/!Scripts/AsadStuff/CollectibleManager.cs, Assets/!Scripts/AsadStuff/CollectibleManager.cs.meta, Assets/!Scripts/AsadStuff/GameManager.cs, Assets/!Scripts/AsadStuff/GameManager.cs.meta, Assets/!Scripts/AsadStuff/Health.cs, Assets/!Scripts/AsadStuff/PlayerSave.cs, Assets/!Scripts/AsadStuff/PlayerSave.cs.meta, Assets/!Scripts/AsadStuff/SaveLoadSystem.cs, Assets/!Scripts/AsadStuff/SaveLoadSystem.cs.meta, ProjectSettings/EditorBuildSettings.asset
Save, Load system that currently saves the player's last location as well as the health at Save. Also inclusion of a collectible system for testing but not yet implemented.
Includes the removal of the old Player and movement and inclusion of the newer one. (Currently Play Game takes to SaveandSaveAndSaveAndSaver for testing for Load functionality).
Next: Load from Menu button,
Saving and Loading State of Enemies
Save and Load for multiple files.
=> Save, Load System

Assets/!Scenes/WorkerTestScene.unity, Assets/!Scripts/Enemies/SpecificEnemyStuff/WorkerBehav.cs, Assets/!Scripts/Player/PlayerHealth.cs, Assets/!Scripts/UI/HealthBar.cs
removed excess code from HealthBar that was creating conflicts, should work as needed now
=> fixes to health bar

Assets/!Scenes/BuildTesting.unity, Assets/!Scenes/Drone Attack/Scripts/ChaserDrone.cs, Assets/!Scripts/AsadStuff/GameManager.cs, Assets/!Scripts/Enemies/HeavyEnemyStuff/HeavyEnemyAI.cs, Assets/!Scripts/Pause Menu/PauseManager.cs, Assets/SkySeries Freebie/FreebieHdri/CloudedSunGlow4k.hdr.meta
all enemies in, journal system and basic camera
=> more adds to the build

Assets/!Scenes/Krystal_Add.unity, Assets/!Scenes/Krystal_Add.unity.meta
=> Krystal Test

Assets/!Scripts/!!Enemies/SpecificEnemyStuff/ExplodingEnemy/ExplodingEnemy.cs
=> Fixed complier error

Assets/!Scenes/!Game/tut.unity, Assets/!Scripts/!!!Player/!!PlayerController/CollisionDetectorRaycast.cs, Assets/!Scripts/!!!Player/!!PlayerController/PlayerMovement.cs, Assets/!Scripts/!!!Player/!!PlayerController/PlayerStatesManager.cs, Assets/!Scripts/!!!Player/Camera/CinemachineCameraController.cs
Checklist :
tweaked the level a bit 
none
=> CONTINUED tutorial

Assets/!Scenes/!Game/tut.unity, ProjectSettings/TagManager.asset
Checklist :
fixed the camera
none
=> fixed the camera dampening

Assets/!Prefabs/!!!Player/AimingCameraUpdated.prefab, Assets/!Prefabs/!!!Player/AimingCameraUpdated.prefab.meta, Assets/!Prefabs/!!!Player/PlayerAidenRitwik.prefab, Assets/!Prefabs/!Enemies/HeavyEnemy/HeavyEnemy.prefab, Assets/!Prefabs/!Enemies/HeavyEnemy/Rock.prefab, Assets/!Scenes/!EnemyScenes/Ritwik_HeavyEnemyTestScene.unity, Assets/!Scenes/Ritwik_AimingCameraRework.unity, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemyAI.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemyIdleState.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemyRock.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemyShootingState.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemySlamAttackState.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemySlamAttackState.cs.meta
Checklist :
HeavyEnemy_scripts changes, this might conflict with any Health or Damage related stuff -_-
HeavyEnemyAI, and most of the HeavyEnemy scripts
=> HeavyEnemy_Updated_with_UniTask

Assets/!Prefabs/!Enemies/Traps/LaserBeam.prefab, Assets/!Prefabs/!Enemies/Traps/LaserBeam.prefab.meta, Assets/!Prefabs/!Enemies/Worker/Worker.prefab, Assets/!Scenes/!EnemyScenes/Diego_Traps.unity, Assets/!Scenes/!EnemyScenes/Diego_Traps.unity.meta, Assets/!Scripts/!Traps.meta, Assets/!Scripts/!Traps/LaserBeam.cs, Assets/!Scripts/!Traps/LaserBeam.cs.meta, Assets/!Scripts/!Traps/LaserWallGenerator.cs, Assets/!Scripts/!Traps/LaserWallGenerator.cs.meta, Assets/!Scripts/!Traps/SpikeTrap.cs, Assets/!Scripts/!Traps/SpikeTrap.cs.meta
Made the initial versions of the traps, and made a worker prefab available
Checklist :
-Made Worker Prefab
-Made Initial version of lasergrid trap and spike trap.
-SpikeTrap
-LaserGridWallGenerator
-LaserBeam
=> Traps and Worker Prefab

Assets/!Prefabs/!Enemies/HeavyEnemy/HeavyEnemy.prefab, Assets/!Prefabs/!Enemies/Traps/Drone.prefab, Assets/!Prefabs/!Enemies/Worker/Worker.prefab
Checklist :
- [✔ ] Have a description of what was done.
- [✔] List of scripts that were worked on.
- [✔] Pull main into your branch. 
- [✔] Fix any merge errors.
Added EnemyDamageComponent
Added HealthBarPrefab, adjusted position above enemy capsules & hooked up to damage component
Enemy Prefabs for Worker, Drone and HeavyEnemy
***still need to add to prefab for Exploder enemy @Clanka-Clanker let me know when prefab is ready
=> PR for adding healthbar and damage component to enemy prefabs

Assets/!Scenes/!Game/tut.unity, Assets/!Scripts/!!!Player/!!PlayerController/PlayerMovement.cs, ProjectSettings/Packages/com.unity.probuilder/Settings.json
=> fixed slope movement

Assets/!Prefabs/!!!Player/Javelin.prefab, Assets/!Scripts/!!!Player/JavelinStuff/JavelinController.cs, Assets/!Scripts/!!!Player/JavelinStuff/PlayerJavelinThrow.cs
Checklist :
Damage System is attached 
Javelin Throw System is reworked 
JavelinController
PlayerJavelinThrow
=> JavelinDamage_Fixes_and_JavelinThrow

Assets/!Scenes/!Game/tut.unity, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/ExplodingEnemy/ExplodingEnemy.cs, ProjectSettings/Packages/com.unity.probuilder/Settings.json
Knockback no longer has 3 calling functions to it, and wont have 3 different knock backs, Will now have to add ledge detection and finalize and fix movement
Checklist :
Knockback does work properly, need to fix ledge detection and proper movement
Get double check from joshua i didnt mess with his damage system because i always do something messed up
yay
-Confirmed by jaxson
Exploding enemy - Asad
=> It WORKS somewhat

Assets/!Scenes/!Game/tut.unity, Assets/!Scripts/!!!Player/!!PlayerController/PlayerMovement.cs, Assets/!Scripts/!!!Player/!!PlayerController/PlayerNEW.prefab, Assets/!Scripts/!!!Player/!!PlayerController/PlayerNEW.prefab.meta, ProjectSettings/Packages/com.unity.probuilder/Settings.json
Checklist :
added wallrun block to stop reattaching to same wall
for merge please use tut scene from main not from my brance only things that need to be merged from my end are the script and the new prefab
PlayerMovement.cs
=> added wallrun block to stop attaching to same wall

Assets/!Scripts/!!!Player/Camera/CinemachineCameraController.cs, ProjectSettings/Packages/com.unity.probuilder/Settings.json
Checklist :
Removed the extra orbital settings in the camera controller script as they are readily available through the cinemachine freelook camera.
CinemachineCameraController.cs
=> Camera Controller Redundancy Removal

.github/copilot-instructions.md, Assets/!Prefabs/!Enemies/Exploda/ExplodingEnemyFixed.prefab, Assets/!Scenes/!Game/tut_Josh.unity, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/ExplodingEnemy/ExplodingEnemy.cs, ProjectSettings/Packages/com.unity.probuilder/Settings.json
ExplodingEnemy script adjusted to re-implement Damage system for each explosion Radius.
Checklist :
ExplodingEnemy script adjusted to re-implement Damage system for each explosion Radius.
ExplodingEnemy prefab also updated with the profiles so the player can receive damage accordingly.
ExplodingEnemy.cs
=> Exploding Enemy Script

Assets/!Prefabs/!!!Player/Player.prefab, Assets/!Scripts/!!!Player/Camera/CinemachineCameraController.cs
Checklist :
Modified the player prefab's freelook cinemachine component to use World Space for it's binding mode instead of Simple Follow With World Up. Allows for the option to change x-damping which was then set to 0 on each of the orbit rings.
CinemachineCameraController
=> Camera Strafing Issue Resolved

Assets/!Prefabs/!Enemies/HeavyEnemy/Rock.prefab, Assets/!Scenes/!EnemyScenes/Ritwik_HeavyEnemyTestScene.unity, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemyAI.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemyRock.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemyShootingState.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemySlamAttackState.cs, Assets/!Scripts/Knockback_System-_-.meta, Assets/!Scripts/Knockback_System-_-/KnockbackData.cs, Assets/!Scripts/Knockback_System-_-/KnockbackData.cs.meta, Assets/!Scripts/Knockback_System-_-/KnockbackReceiver.cs, Assets/!Scripts/Knockback_System-_-/KnockbackReceiver.cs.meta
Checklist :
added 2 new knockback scripts 
KnockbackData
KnockbackReciver
Most of HeavyEnemy Scripts
=> Knockback fixes

Assets/!Scripts/!!!Player/!!PlayerController/PlayerNEW.prefab
Checklist :
Modified the new player prefab with the updated camera fixes for strafing
NA
=> Updated PlayerNEW.prefab

Assets/!Prefabs/!Enemies/Traps/WallyThornyPrefab.prefab, Assets/!Prefabs/!Enemies/Traps/WallyThornyPrefab.prefab.meta, Assets/!Scenes/!Game/Kaylani_Tut.unity, Assets/!Scenes/!Game/Kaylani_Tut.unity.meta, Assets/!Scripts/!Traps/WallThorns.cs, Packages/manifest.json, Packages/packages-lock.json
Add lerping to wall thorns
created a new prefab named WallyThornyPrefab
edited WallThorns.cs
Checklist :
Added lerping to wall thorns
created a new prefab named WallyThornyPrefab
edited WallThorns.cs
WallThorns.cs
=> Wall Thorn trap fix

Assets/!Scenes/!Game/tut.unity, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/ExplodingEnemy/ExplodingEnemy.cs
Checklist :
Added instant explosion to inner sphere
Yea
-help from the goat, colton
Explosion enemy
=> Exploding enemy asad oof

Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/KF_PE_EnemyWorker_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_Textures/KF_Shader's/KF_Zach_M/KF_HoloShader_MapSphere.unitypackage.meta, Assets/!Scenes/!Game/Krystal_tutcity.unity
=> Krystal branch

Assets/!Scenes/!Game/shane_tutcity.unity, Assets/!Scripts/UI/MyDebugUI.cs, Assets/!Scripts/UI/MyDebugUI.cs.meta, DebugSettings/DebugSettings.json, ProjectSettings/Packages/com.unity.probuilder/Settings.json, ProjectSettings/TagManager.asset
Checklist :
added debug tool 
MyDebugUI.cs
=> added Hisham bug fixing tool

Assets/!Scripts/!!!Player/!!PlayerController/PlayerMovement.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemyAI.cs, Assets/!Scripts/!!Enemies/SpecificEnemyStuff/HeavyEnemyStuff/HeavyEnemySlamAttackState.cs
Checklist :
HeavyEnemy_DamageFix
PlayerController
HeavyEnemyAI
HeavyEnemySlamAttackState
=> HeavyEnemy_DamageFix

Assets/!Scenes/!Game/tut_Josh.unity, Assets/!Scripts/!!!Player/Journal-Relic/InventoryManager.cs, Assets/!Scripts/!!!Player/Journal-Relic/Item.cs, Assets/!Scripts/JoshuaC_Scripts/Buttons/Load Button.cs, Assets/!Scripts/JoshuaC_Scripts/CheckpointSystem.cs, Assets/!Scripts/JoshuaC_Scripts/FadetoBlack.cs, Assets/!Scripts/JoshuaC_Scripts/FadetoBlack.cs.meta, Assets/!Scripts/JoshuaC_Scripts/PlayerSave.cs, Assets/!Scripts/JoshuaC_Scripts/SaveLoadSystem.cs
Checklist :
Publics set for ItemName, ItemSprite, ItemDescription allowing for reference.
Load Button functionality updated to factor in SaveLoadSystem() in addition to loading scene.
PlayerSave updated to allow for calling CharacterController remotely. Inventory Canvas grabbed.
Save functionality and Load functionality updated to allow for Adding items on Scene Load.
InventoryManager
Item
Load Button
PlayerSave
SaveLoadSystem
=> JoshCImplementation

Assets/!Scripts/!!!Player/!!PlayerController/PlayerMovement.cs
Added a new method to update rotation logic on wall runs based on the normal that gets updated as the player switches wall curvatures (curved walls)
Checklist :
Made changes to the PlayerMovement.cs in the void WallRun() function and added a new method UpdateWallRunRotation(Vector3 wallNormal, bool rightWall), also modified the void StartWallRunning() as rotation logic was moved to the new method
PlayerMovement.cs
=> Tweaked WallRun Logic For Continuous Rotation Updates

Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/Enemy Prefabs/KF_P_Large_Enemy_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/Enemy Prefabs/KF_P_WorkerEnemyShader_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/Extra VFX/KF_P_EnemyHitVFX_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/Extra VFX/KF_P_LightningCharge_Cone_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/Extra VFX/KF_P_LightningSparkVFX_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/Extra VFX/KF_P_PurpleBurstVFX_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/Extra VFX/KF_P_SmallExplosionVFX_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_CatapultCrater_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_CatapultWaymarker_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_Checkpoint_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_DashAttackVFX_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_JavelinHitVFX_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_LightningCharge_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_SelfDestructVFX_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_StylizedSmokeVFX_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_Weapon_Interactable_Tut_Peter.unitypackage.meta, Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/_Peters.unitypackages/KF_Peter_unitypackages/KF_P_Weapon_Trail_Peter.unitypackage.meta, Assets/!Assets/MasterStylizedFX/MSFURP.unitypackage.meta, Assets/!Assets/MasterStylizedFX/MSFURP2D.unitypackage.meta, Assets/!Assets/MasterStylizedFX/MSFURPWebGLFix.unitypackage.meta, Assets/!Assets/Settings/UniversalRenderPipelineGlobalSettings.asset, Assets/!Prefabs/BuildNumber.prefab
=> Level fixes

Assets/!Assets/KrystalAssetsUpload/KF_UI_Assets/MainMenu_Ghazal/MainMenu_Render_Ghazal/Materials.meta, Assets/!Assets/MasterStylizedFX/MSFURP2D.unitypackage.meta, Assets/!Assets/MasterStylizedFX/MSFURPWebGLFix.unitypackage.meta, Assets/!Assets/Settings/UniversalRenderPipelineGlobalSettings.asset, Assets/!Prefabs/!Enemies/Exploda/ExplodingEnemyFixed.prefab, Assets/!Prefabs/!Enemies/HeavyEnemy/HeavyEnemy.prefab, Assets/!Prefabs/!Enemies/Worker/Worker.prefab, Assets/!Scenes/!Game/!MenuScenes/Kadeem_MainMenu.unity, Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/VFXManager.asset
=> Quick fixes

Assets/!Assets/KrystalAssetsUpload/KF_ParticleEffects/KF_Peter/Disntegrate/Enemy_Worker.prefab, Assets/!Prefabs/!Enemies/HeavyEnemy/HeavyEnemy.prefab, Assets/!Prefabs/!Enemies/Worker/Worker.prefab
Checklist :
Added the texture for the worker prefab and implemented the death particle vfx/dissolve
=> Worker Prefab Death VFX + Model Textures

Assets/!Scripts/!!!Player/JavelinStuff/PlayerJavelinThrow.cs
Checklist :
Javelin visual bug fixed -_-
PlayerJavelinThrow
=> Javelin visual bug fixed -_-

Assets/!Scenes/!Game/Asad_LevelDesignMesh.unity, ProjectSettings/EditorBuildSettings.asset
=> Lol forgot to save
